"""
Django  settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import secrets
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


#Quick-start development settings - unsuitable for production
#See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-_gi)k=)ux!i+)b1ls$7-$itgk$p9)b#lgbty^exf*m_q2$&4qx',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', '0') == '1'

def _lista_de(variable, por_defecto):
    """Los valores de una variable separados por comas, o `por_defecto`.

    Args:
        variable: Nombre de la variable de entorno, p. ej. 'DJANGO_ALLOWED_HOSTS'.
        por_defecto: Lista que vale cuando la variable no está o está vacía.
    """
    crudo = os.getenv(variable, '')
    return [x.strip() for x in crudo.split(',') if x.strip()] or por_defecto


# Dominios que esta instalación acepta servir.
#
# El dominio lo decide el hosting, no el código, así que la lista sale de
# DJANGO_ALLOWED_HOSTS (nombres separados por comas) y lo de abajo es solo el
# valor por defecto. Con DJANGO_DEBUG=0 y el dominio fuera de la lista, Django
# contesta 400 a todo: es el primer sitio donde mirar si el sitio recién
# mudado no abre.
ALLOWED_HOSTS = _lista_de('DJANGO_ALLOWED_HOSTS', [
    'localhost', '127.0.0.1',
    'dashboardgps.qd.je',
])

# El origen completo (con https:// y el puerto si lo hubiera) de cada dominio.
# Django lo compara contra la cabecera Origin de cada POST; si falta el
# dominio nuevo, el login contesta «CSRF verification failed» aunque el correo
# y la clave estén bien.
CSRF_TRUSTED_ORIGINS = _lista_de('DJANGO_CSRF_TRUSTED_ORIGINS', [
    'https://dashboardgps.qd.je',
])

# Subcarpeta en la que vive la aplicación cuando no está en la raíz del
# dominio: '/dashboard' para https://dominio.com/dashboard/.
#
# Hay que ponerla siempre que la aplicación no esté en la raíz. Passenger
# avisa de la subcarpeta por su cuenta (la variable SCRIPT_NAME de WSGI) y con
# eso `reverse()`, `{% url %}` y los redirect ya salen bien, pero `{% static %}`
# no: Django calcula STATIC_URL una sola vez, al cargar el WSGI, cuando
# todavía no hay ninguna petición de la que sacar el prefijo, y se queda con
# ese valor para siempre. Por eso la subcarpeta se dice aquí y no se adivina.
#
# Ponerla de más, con un Passenger que sí avisa, no duplica el prefijo: este
# valor sustituye al que manda el servidor, no se le suma. Ponerla cuando la
# aplicación está en la raíz sí rompe los enlaces, así que tiene que decir la
# verdad.
FORCE_SCRIPT_NAME = os.getenv('DJANGO_FORCE_SCRIPT_NAME', '').strip().rstrip('/') or None

GPS_API_BASE_URL = os.getenv('GPS_API_BASE_URL', 'https://api.service24gps.com/api/v1')
GPS_APIKEY = os.getenv('GPS_APIKEY', '')
GPS_USERNAME = os.getenv('GPS_USERNAME', '')
GPS_PASSWORD = os.getenv('GPS_PASSWORD', '')

# Acceso de emergencia al dashboard, indexado por correo. `empresas: None`
# significa acceso total (todas las pestañas y el mapa de flota).
#
# Las cuentas de verdad son filas de tracking.models.DashboardUsuario y se
# dan de alta desde /admin/, una por persona y con la clave hasheada. Esto de
# aquí es solo la puerta de atrás para dos casos: que la base de datos no
# conteste, y que todavía no exista ninguna cuenta.
#
# En desarrollo trae cuentas por defecto para no tener que configurar nada. En
# producción (DJANGO_DEBUG apagado) solo existe la cuenta que alguien haya
# configurado a mano con sus dos variables: así las claves escritas aquí
# abajo, que están en un repositorio público, no abren nada en el servidor.
#
# Las llaves quedan en minúsculas porque el login normaliza así el correo que
# se escribe en el formulario.
_CUENTAS = (
    # (sufijo de las variables, correo por defecto, clave por defecto, empresas)
    ('ADMIN',   'admin@rastrelital.com',   'Admin',   None),
    ('PROCAPS', 'procaps@rastrelital.com', 'Procaps', ('PROCAPS',)),
    ('DITAR',   'ditar@rastrelital.com',   'Ditar',   ('DITAR',)),
    ('RELIANZ', 'relianz@rastrelital.com', 'relianz', ('RELIANZ',)),
)

def _catalogo_de(cuentas, con_defectos):
    """Arma el acceso de emergencia y se planta si el .env quedó mal.

    Args:
        cuentas: Tuplas (sufijo, correo, clave, empresas) como `_CUENTAS`.
        con_defectos: Si es falso, una cuenta existe solo cuando sus dos
            variables están puestas. Va apagado en producción, donde las
            claves de este archivo no pueden abrir nada.

    Las cuatro cosas que revisa abrirían la puerta en silencio si pasaran:
    un correo en blanco deja entrar con el campo vacío, una clave en blanco
    deja entrar sin contraseña, un correo repetido le da a una cuenta los
    permisos de la otra (gana la última, y la primera desaparece), y media
    cuenta configurada deja la otra mitad en el valor público del archivo.
    Con un diccionario por comprensión las cuatro se ven igual de bien que
    una configuración correcta, así que mejor reventar al arrancar.

    Raises:
        ImproperlyConfigured: Si alguna cuenta quedó a medias, sin correo,
            sin clave, con algo que no es un correo, o repitiendo el de otra.
    """
    catalogo = {}
    for sufijo, correo_defecto, clave_defecto, empresas in cuentas:
        var_correo = f'DASHBOARD_CORREO_{sufijo}'
        var_clave = f'DASHBOARD_CLAVE_{sufijo}'
        correo_env = os.getenv(var_correo)
        clave_env = os.getenv(var_clave)
        if correo_env is None and clave_env is None:
            if not con_defectos:
                continue
            correo_env, clave_env = correo_defecto, clave_defecto
        elif correo_env is None or clave_env is None:
            raise ImproperlyConfigured(
                f'{var_correo} y {var_clave} van juntas: pon las dos, o '
                f'ninguna. Con una sola, la otra mitad de la cuenta se '
                f'quedaría con el valor de ejemplo del código.')
        correo = correo_env.strip().lower()
        clave = clave_env
        if not correo:
            raise ImproperlyConfigured(
                f'{var_correo} está vacía. Ponle un correo o bórrala del .env '
                f'para volver al valor por defecto.')
        if '@' not in correo:
            raise ImproperlyConfigured(
                f'{var_correo} vale {correo!r}, que no es un correo: al '
                f'dashboard se entra con el correo completo.')
        if correo in catalogo:
            raise ImproperlyConfigured(
                f'{var_correo} repite el correo {correo!r}, que ya usa otra '
                f'cuenta. Cada cuenta necesita el suyo.')
        if not clave:
            raise ImproperlyConfigured(
                f'{var_clave} está vacía, y una clave vacía deja entrar a '
                f'{correo!r} sin escribir nada.')
        catalogo[correo] = {'clave': clave, 'empresas': empresas}
    return catalogo


DASHBOARD_USUARIOS = _catalogo_de(_CUENTAS, con_defectos=DEBUG)

# TEMPORAL: cuenta del botón «acceso sin cuenta» del login. La clave es
# aleatoria por arranque para que nadie entre con ella por el formulario;
# el botón entra por su propia vista. Al borrar esta entrada, todas las
# sesiones de invitado mueren solas. Buscar TEMPORAL para quitarlo todo.
DASHBOARD_USUARIOS['invitado'] = {
    'clave': secrets.token_urlsafe(32),
    'empresas': None,
}

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

SESSION_COOKIE_AGE = 12 * 60 * 60
SESSION_SAVE_EVERY_REQUEST = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

# La cookie se manda solo a la subcarpeta de la aplicación. Con el valor de
# fábrica ('/'), dos aplicaciones distintas del mismo dominio —cosa normal en
# un hosting compartido— se pisarían la sesión la una a la otra.
SESSION_COOKIE_PATH = FORCE_SCRIPT_NAME or '/'
CSRF_COOKIE_PATH = SESSION_COOKIE_PATH

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Cache del dashboard.
#
# Aquí está todo el peso de la aplicación: services.py guarda las alertas de
# cada día y las timbradas de cada bus con TTL de hasta 24 h, y sin cache cada
# consulta le vuelve a pegar al API día por día y bus por bus.
#
# Sin REDIS_URL queda el cache en memoria del proceso, y con Passenger eso es
# justo lo que hace falta: Passenger levanta procesos de Python que siguen
# vivos entre peticiones, así que el cache se llena una vez y lo aprovechan
# las siguientes. Es lo mismo que pasa en desarrollo, y por eso ninguno de los
# dos necesita un Redis al lado.
#
# REDIS_URL se pone solo si algún día la aplicación corre en varios procesos
# que tengan que compartir el cache, o en un hosting que congele el proceso
# entre peticiones (los serverless tipo Vercel o Lambda), donde un cache en
# memoria arrancaría vacío casi siempre.
#
# Ojo en hosting compartido: Passenger apaga el proceso tras unos minutos sin
# visitas (PassengerPoolIdleTime), y al apagarse el cache en memoria se va con
# él. La primera visita después de un rato largo es la lenta.
REDIS_URL = os.getenv('REDIS_URL', '')

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            # El prefijo deja convivir varios despliegues en la misma base de
            # Redis sin que se pisen las llaves.
            'KEY_PREFIX': os.getenv('REDIS_PREFIX', 'dashboard-gps'),
            'OPTIONS': {
                # Sin tope de tiempo, un Redis que no contesta deja colgada la
                # petición entera hasta que el hosting la corta. Es preferible
                # que falle rápido y se vea el error.
                'socket_connect_timeout': 3,
                'socket_timeout': 3,
            },
        },
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'dashboard-gps',
            # El tope de fábrica son 300 entradas y se llena rápido: es una
            # por día consultado más una por bus, y al pasarse Django tira un
            # tercio del cache.
            'OPTIONS': {'MAX_ENTRIES': 5000},
        },
    }


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracking',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tracking.middleware.LoginRequeridoMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Con DATABASE_URL puesto se usa Postgres (Supabase); ahí vive la flota (ver
# tracking.models.FlotaVehiculo). Sin la variable queda sqlite, que basta para
# desarrollo local sin credenciales de Supabase a mano.
DATABASE_URL = os.getenv('DATABASE_URL', '')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL, conn_max_age=600, ssl_require=True,
        ),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Quien sirve los estáticos es WhiteNoise (está en MIDDLEWARE), no Apache:
# lee los archivos de STATIC_ROOT, así que en el servidor hay que correr
# `python manage.py collectstatic` después de cada despliegue. Sin eso el
# dashboard carga sin CSS y el /admin/ se ve en texto plano.
#
# STATIC_URL lleva delante la subcarpeta, si la hay, porque es la URL que
# acaba escrita en el HTML y el navegador la pide tal cual. WhiteNoise, en
# cambio, compara contra la ruta que le llega ya sin la subcarpeta (Passenger
# se la queda en SCRIPT_NAME): esa resta la hace él solo, mirando
# FORCE_SCRIPT_NAME, y por eso las dos puntas coinciden.
STATIC_URL = f'{FORCE_SCRIPT_NAME}/static/' if FORCE_SCRIPT_NAME else '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# collectstatic deja además una copia .gz de cada archivo de texto y
# WhiteNoise sirve esa cuando el navegador la acepta. En un hosting compartido
# el ancho de banda y la CPU son el cuello de botella, y comprimir una vez al
# desplegar sale más barato que comprimir en cada visita.
#
# Es la versión *sin* manifiesto a propósito: la que renombra los archivos con
# un hash revienta el despliegue entero si una plantilla pide con
# `{% static %}` un archivo que no existe, y aquí hay 34 imágenes llamadas a
# mano en home.html.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}


# Tipo de la columna `id` que Django le pone a un modelo que no declara clave
# primaria. Las tablas que ya están en Supabase se crearon con BigAutoField
# (bigint), y aquí se dice explícitamente para que siga siendo así.
#
# Django 6.0 ya usa BigAutoField por defecto, así que esta línea no cambia
# nada hoy. Está por si algún día hay que bajar a Django 5.2 LTS —porque el
# hosting no tenga Python 3.12—: ahí el valor de fábrica es AutoField
# (integer), y sin esta línea Django creería que las tablas van en integer y
# `makemigrations` generaría un ALTER para encoger las columnas de la base de
# producción. La línea vale para las dos versiones y evita esa sorpresa.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
