"""
Django  settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import secrets
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


#Quick-start development settings - unsuitable for production
#See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'DJANGO_SECRET_KEY',
    'django-insecure-_gi)k=)ux!i+)b1ls$7-$itgk$p9)b#lgbty^exf*m_q2$&4qx',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', '0') == '1'

ALLOWED_HOSTS = [
    'localhost', '127.0.0.1',
    'dashboardgps.qd.je',
    '.onrender.com',
    '.vercel.app',
]

CSRF_TRUSTED_ORIGINS = [
    'https://dashboardgps.qd.je',
    'https://*.onrender.com',
    'https://*.vercel.app',
]

GPS_API_BASE_URL = os.getenv('GPS_API_BASE_URL', 'https://api.service24gps.com/api/v1')
GPS_APIKEY = os.getenv('GPS_APIKEY', '')
GPS_USERNAME = os.getenv('GPS_USERNAME', '')
GPS_PASSWORD = os.getenv('GPS_PASSWORD', '')

# Acceso de emergencia al dashboard, indexado por correo. `empresas: None`
# significa acceso total (todas las pestañas y el mapa de flota).
#
# Las cuentas de verdad son filas de tracking.models.DashboardUsuario y se
# dan de alta desde /admin/, una por persona y con la clave hasheada. Esto de
# aquí es solo la puerta de atrás para dos casos: que la base de datos no
# conteste, y que todavía no exista ninguna cuenta.
#
# En desarrollo trae cuentas por defecto para no tener que configurar nada. En
# producción (DJANGO_DEBUG apagado) solo existe la cuenta que alguien haya
# configurado a mano con sus dos variables: así las claves escritas aquí
# abajo, que están en un repositorio público, no abren nada en el servidor.
#
# Las llaves quedan en minúsculas porque el login normaliza así el correo que
# se escribe en el formulario.
_CUENTAS = (
    # (sufijo de las variables, correo por defecto, clave por defecto, empresas)
    ('ADMIN',   'admin@rastrelital.com',   'Admin',   None),
    ('PROCAPS', 'procaps@rastrelital.com', 'Procaps', ('PROCAPS',)),
    ('DITAR',   'ditar@rastrelital.com',   'Ditar',   ('DITAR',)),
    ('RELIANZ', 'relianz@rastrelital.com', 'relianz', ('RELIANZ',)),
)

def _catalogo_de(cuentas, con_defectos):
    """Arma el acceso de emergencia y se planta si el .env quedó mal.

    Args:
        cuentas: Tuplas (sufijo, correo, clave, empresas) como `_CUENTAS`.
        con_defectos: Si es falso, una cuenta existe solo cuando sus dos
            variables están puestas. Va apagado en producción, donde las
            claves de este archivo no pueden abrir nada.

    Las cuatro cosas que revisa abrirían la puerta en silencio si pasaran:
    un correo en blanco deja entrar con el campo vacío, una clave en blanco
    deja entrar sin contraseña, un correo repetido le da a una cuenta los
    permisos de la otra (gana la última, y la primera desaparece), y media
    cuenta configurada deja la otra mitad en el valor público del archivo.
    Con un diccionario por comprensión las cuatro se ven igual de bien que
    una configuración correcta, así que mejor reventar al arrancar.

    Raises:
        ImproperlyConfigured: Si alguna cuenta quedó a medias, sin correo,
            sin clave, con algo que no es un correo, o repitiendo el de otra.
    """
    catalogo = {}
    for sufijo, correo_defecto, clave_defecto, empresas in cuentas:
        var_correo = f'DASHBOARD_CORREO_{sufijo}'
        var_clave = f'DASHBOARD_CLAVE_{sufijo}'
        correo_env = os.getenv(var_correo)
        clave_env = os.getenv(var_clave)
        if correo_env is None and clave_env is None:
            if not con_defectos:
                continue
            correo_env, clave_env = correo_defecto, clave_defecto
        elif correo_env is None or clave_env is None:
            raise ImproperlyConfigured(
                f'{var_correo} y {var_clave} van juntas: pon las dos, o '
                f'ninguna. Con una sola, la otra mitad de la cuenta se '
                f'quedaría con el valor de ejemplo del código.')
        correo = correo_env.strip().lower()
        clave = clave_env
        if not correo:
            raise ImproperlyConfigured(
                f'{var_correo} está vacía. Ponle un correo o bórrala del .env '
                f'para volver al valor por defecto.')
        if '@' not in correo:
            raise ImproperlyConfigured(
                f'{var_correo} vale {correo!r}, que no es un correo: al '
                f'dashboard se entra con el correo completo.')
        if correo in catalogo:
            raise ImproperlyConfigured(
                f'{var_correo} repite el correo {correo!r}, que ya usa otra '
                f'cuenta. Cada cuenta necesita el suyo.')
        if not clave:
            raise ImproperlyConfigured(
                f'{var_clave} está vacía, y una clave vacía deja entrar a '
                f'{correo!r} sin escribir nada.')
        catalogo[correo] = {'clave': clave, 'empresas': empresas}
    return catalogo


DASHBOARD_USUARIOS = _catalogo_de(_CUENTAS, con_defectos=DEBUG)

# TEMPORAL: cuenta del botón «acceso sin cuenta» del login. La clave es
# aleatoria por arranque para que nadie entre con ella por el formulario;
# el botón entra por su propia vista. Al borrar esta entrada, todas las
# sesiones de invitado mueren solas. Buscar TEMPORAL para quitarlo todo.
DASHBOARD_USUARIOS['invitado'] = {
    'clave': secrets.token_urlsafe(32),
    'empresas': None,
}

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

SESSION_COOKIE_AGE = 12 * 60 * 60
SESSION_SAVE_EVERY_REQUEST = True

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Cache del dashboard.
#
# Aquí está todo el peso de la aplicación: services.py guarda las alertas de
# cada día y las timbradas de cada bus con TTL de hasta 24 h, y sin cache cada
# consulta le vuelve a pegar al API día por día y bus por bus.
#
# Con REDIS_URL puesto se usa Redis. Eso es lo que hace falta en un hosting
# serverless como Vercel, donde cada petición puede caer en una instancia
# distinta y las instancias se congelan entre peticiones: un cache en memoria
# arrancaría vacío casi siempre. Sin la variable queda el cache en memoria del
# proceso, que le basta a un servidor de toda la vida (Render) y al desarrollo
# local, y así ninguno de los dos necesita un Redis al lado.
REDIS_URL = os.getenv('REDIS_URL', '')

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            # El prefijo deja convivir varios despliegues en la misma base de
            # Redis sin que se pisen las llaves.
            'KEY_PREFIX': os.getenv('REDIS_PREFIX', 'dashboard-gps'),
            'OPTIONS': {
                # Sin tope de tiempo, un Redis que no contesta deja colgada la
                # petición entera hasta que el hosting la corta. Es preferible
                # que falle rápido y se vea el error.
                'socket_connect_timeout': 3,
                'socket_timeout': 3,
            },
        },
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'dashboard-gps',
            # El tope de fábrica son 300 entradas y se llena rápido: es una
            # por día consultado más una por bus, y al pasarse Django tira un
            # tercio del cache.
            'OPTIONS': {'MAX_ENTRIES': 5000},
        },
    }


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tracking',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tracking.middleware.LoginRequeridoMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Con DATABASE_URL puesto se usa Postgres (Supabase); ahí vive la flota (ver
# tracking.models.FlotaVehiculo). Sin la variable queda sqlite, que basta para
# desarrollo local sin credenciales de Supabase a mano.
DATABASE_URL = os.getenv('DATABASE_URL', '')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL, conn_max_age=600, ssl_require=True,
        ),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-mx'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'
