# Generated by Django 6.0.7 on 2026-08-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=32, unique=True)),
                ('clave_hash', models.CharField(max_length=128)),
                ('empresas', models.CharField(blank=True, help_text='Lista separada por comas de entre PROCAPS, DITAR, RELIANZ (vacío = todas).', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'usuario del dashboard',
                'verbose_name_plural': 'usuarios del dashboard',
            },
        ),
    ]
