# Generated by Django 6.0.7 on 2026-08-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlotaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('no_interno', models.CharField(db_index=True, max_length=10)),
                ('ciudad', models.CharField(blank=True, max_length=60)),
                ('tipo_vehiculo', models.CharField(blank=True, max_length=30)),
                ('marca', models.CharField(blank=True, max_length=40)),
                ('modelo', models.CharField(blank=True, max_length=10)),
                ('capacidad_sillas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contrato', models.CharField(blank=True, max_length=40)),
                ('ruta', models.CharField(blank=True, max_length=40)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'vehículo de flota',
                'verbose_name_plural': 'flota (vehículos)',
                'ordering': ['no_interno'],
            },
        ),
    ]
