# Generated by Django 6.0.7 on 2026-08-18 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_flotavehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardusuario',
            name='invitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitados', to='tracking.dashboardusuario'),
        ),
        migrations.AddField(
            model_name='dashboardusuario',
            name='puede_invitar',
            field=models.BooleanField(default=False, help_text='Puede dar de alta invitaciones para otras cuentas.'),
        ),
        migrations.AlterField(
            model_name='dashboardusuario',
            name='clave_hash',
            field=models.CharField(blank=True, help_text='En blanco mientras la invitación no ha sido reclamada.', max_length=128),
        ),
        migrations.AlterField(
            model_name='dashboardusuario',
            name='usuario',
            field=models.CharField(help_text='Nombre de usuario, o correo para las cuentas invitadas.', max_length=254, unique=True),
        ),
    ]
