# Generated by Django 6.0.7 on 2026-09-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_delete_dashboardusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(help_text='Con este correo entra al dashboard.', max_length=254, unique=True, verbose_name='correo')),
                ('nombre', models.CharField(blank=True, help_text='Opcional, para saber de quién es la cuenta.', max_length=80)),
                ('clave_hash', models.CharField(max_length=128, verbose_name='clave')),
                ('acceso_total', models.BooleanField(default=False, help_text='Ve todas las empresas y además el mapa de flota.', verbose_name='acceso total')),
                ('empresas', models.CharField(blank=True, help_text='Empresas que ve, separadas por comas: PROCAPS, DITAR, RELIANZ. Se ignora si tiene acceso total.', max_length=200)),
                ('activo', models.BooleanField(default=True, help_text='Al desmarcarlo la cuenta deja de entrar, y la sesión que tuviera abierta se cierra sola en la siguiente página.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_ingreso', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'usuario del dashboard',
                'verbose_name_plural': 'usuarios del dashboard',
                'ordering': ['correo'],
            },
        ),
    ]
